# Credits

This is heavily based on https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used.


PyTorch a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [1]:
import torch

Construct a $5\times 3$ matrix, uninitialized

In [2]:
x = torch.Tensor(5, 3)
print(x)

tensor([[1.0337, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])


Construct a randomly initialized matrix

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.9756, 0.8060, 0.1510],
        [0.1956, 0.2441, 0.4502],
        [0.4343, 0.8721, 0.9399],
        [0.2273, 0.6235, 0.7112],
        [0.2476, 0.5775, 0.8831]])


Get its size

In [4]:
print(x.size())

torch.Size([5, 3])


**NOTE**: `torch.Size` is in fact a tuple, so it supports the same operations that a tuple supports.

In [5]:
x[1:3] = 2
print(x)

tensor([[0.9756, 0.8060, 0.1510],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.2273, 0.6235, 0.7112],
        [0.2476, 0.5775, 0.8831]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [6]:
# 1
T = torch.Tensor(2, 17)

# 2
T_float = torch.FloatTensor(3, 1)

# 3
T_long = torch.LongTensor(5, 2, 1)
print(T_long.size())
T_long[:] = 7
print(T_long.size())
print(T_long)

# 4
T_byte = torch.ByteTensor(5)
print(T_byte)
T_byte[1:4] = 1
print(T_byte)

torch.Size([5, 2, 1])
torch.Size([5, 2, 1])
tensor([[[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]]])
tensor([154, 232,  29,  63,   0], dtype=torch.uint8)
tensor([154,   1,   1,   1,   0], dtype=torch.uint8)


## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [7]:
y = torch.rand(5, 3)
print(x + y)

tensor([[1.0255, 1.3576, 0.6633],
        [2.3971, 2.2297, 2.5868],
        [2.6694, 2.0385, 2.5191],
        [0.7571, 1.4910, 1.4880],
        [0.5763, 1.2500, 1.0894]])


### 2.2 Addition: syntax 2

In [8]:
print(torch.add(x, y))

tensor([[1.0255, 1.3576, 0.6633],
        [2.3971, 2.2297, 2.5868],
        [2.6694, 2.0385, 2.5191],
        [0.7571, 1.4910, 1.4880],
        [0.5763, 1.2500, 1.0894]])


### 2.3 Addition: giving an output tensor

In [9]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.0255, 1.3576, 0.6633],
        [2.3971, 2.2297, 2.5868],
        [2.6694, 2.0385, 2.5191],
        [0.7571, 1.4910, 1.4880],
        [0.5763, 1.2500, 1.0894]])


### 2.4 Addition: in-place

adds `x` to `y`

In [10]:
y.add_(x)
print(y)

tensor([[1.0255, 1.3576, 0.6633],
        [2.3971, 2.2297, 2.5868],
        [2.6694, 2.0385, 2.5191],
        [0.7571, 1.4910, 1.4880],
        [0.5763, 1.2500, 1.0894]])


**NOTE**: Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [11]:
print(x[:, 1])

tensor([0.8060, 2.0000, 2.0000, 0.6235, 0.5775])


**Read later**: 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

In [49]:
a = torch.randn(2, 2)
b = torch.randn(2, 2)
print(f"a = {a}")
print(f"b = {b}")

print("\n1. Multiplication " + "-"*20)

# 1
m = a * b
print(f"m = {m}")

print("\n2. Mul in-place " + "-"*20)

# 2
print(torch.mul(a, b))
print(a.mul_(b))

print("\n3. Division " + "-"*20)


# 3
d = torch.div(a, b)
print(f"d = {d}")

print("\n4. Matrix multiplication " + "-"*20)

# 4 
a = torch.randn(2, 4)
b = torch.randn(4, 2)
print(f"a = {a}")
print(f"b = {b}")
print(torch.mm(a, b))

a = tensor([[ 1.1826,  1.1559],
        [-0.4319,  1.1464]])
b = tensor([[ 0.4498, -1.2423],
        [-1.1122, -1.6171]])

1. Multiplication --------------------
m = tensor([[ 0.5320, -1.4359],
        [ 0.4804, -1.8538]])

2. Mul in-place --------------------
tensor([[ 0.5320, -1.4359],
        [ 0.4804, -1.8538]])
tensor([[ 0.5320, -1.4359],
        [ 0.4804, -1.8538]])

3. Division --------------------
d = tensor([[ 1.1826,  1.1559],
        [-0.4319,  1.1464]])

4. Matrix multiplication --------------------
a = tensor([[ 0.4148,  1.0867, -1.4404, -0.6440],
        [ 0.2897,  0.2659,  0.3649,  1.3502]])
b = tensor([[-1.5133, -0.9454],
        [-0.0579,  1.0869],
        [ 2.0128,  0.3585],
        [-2.0952, -0.4879]])
tensor([[-2.2407,  0.5867],
        [-2.5484, -0.5128]])


## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [50]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [13]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value: the `numpy()` method provides a *view* of the original tensor, not a copy.

In [14]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [15]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a NumPy array
3. now convert it back to a torch tensor

All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

In [55]:
T = torch.ones(5, 2)
print(T)
T_np = T.numpy()
print(T_np)
T_tensor = torch.from_numpy(T_np)
print(T_tensor)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [16]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # Notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # This is meant as a tensor to be run on the GPU.
    # The .cuda() does this to any parameter it is applied to.
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machine.")

tensor([[0.9756, 0.8060, 0.1510],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.2273, 0.6235, 0.7112],
        [0.2476, 0.5775, 0.8831]], device='cuda:0')
tensor([[1.0255, 1.3576, 0.6633],
        [2.3971, 2.2297, 2.5868],
        [2.6694, 2.0385, 2.5191],
        [0.7571, 1.4910, 1.4880],
        [0.5763, 1.2500, 1.0894]], device='cuda:0')
tensor([[2.0011, 2.1636, 0.8142],
        [4.3971, 4.2297, 4.5868],
        [4.6694, 4.0385, 4.5191],
        [0.9843, 2.1144, 2.1992],
        [0.8239, 1.8275, 1.9725]], device='cuda:0')
